// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package components

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets\PerformanceMonitor.ico
var resourcePerformanceMonitorIcoData []byte
var resourcePerformanceMonitorIco = &fyne.StaticResource{
	StaticName:    "assets\\PerformanceMonitor.ico",
	StaticContent: resourcePerformanceMonitorIcoData,
}
