// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package themes

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets\PerformanceMonitor.ico
var resourcePerformanceMonitorIcoData []byte
var resourcePerformanceMonitorIco = &fyne.StaticResource{
	StaticName:    "assets\\PerformanceMonitor.ico",
	StaticContent: resourcePerformanceMonitorIcoData,
}

//go:embed assets\ShieldCheck.ico
var resourceShieldCheckIcoData []byte
var resourceShieldCheckIco = &fyne.StaticResource{
	StaticName:    "assets\\ShieldCheck.ico",
	StaticContent: resourceShieldCheckIcoData,
}

//go:embed assets\ShieldX.ico
var resourceShieldXIcoData []byte
var resourceShieldXIco = &fyne.StaticResource{
	StaticName:    "assets\\ShieldX.ico",
	StaticContent: resourceShieldXIcoData,
}
